#!/usr/bin/env bash
set -e

STATUS=0

if ! go version; then
  echo "You need to install Go 1.2" >&2
  STATUS=1
fi

if type -p make >/dev/null; then
  make --version | head -1
else
  echo "You need the \`make' command" >&2
  STATUS=1
fi

if [ $STATUS -eq 0 ]; then
  echo "Everything OK."
fi

exit $STATUS
